//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XPOCollection_Teste.standby_org
{

    public partial class tb_clientes : XPLiteObject
    {
        int fcl_id;
        [Key(true)]
        public int cl_id
        {
            get { return fcl_id; }
            set { SetPropertyValue<int>(nameof(cl_id), ref fcl_id, value); }
        }
        string fcl_nome;
        public string cl_nome
        {
            get { return fcl_nome; }
            set { SetPropertyValue<string>(nameof(cl_nome), ref fcl_nome, value); }
        }
        string fcl_telefone;
        [Size(15)]
        [ColumnDbDefaultValue("('------------')")]
        public string cl_telefone
        {
            get { return fcl_telefone; }
            set { SetPropertyValue<string>(nameof(cl_telefone), ref fcl_telefone, value); }
        }
        string fcl_cpf;
        [Size(18)]
        [ColumnDbDefaultValue("('SEM CPF')")]
        public string cl_cpf
        {
            get { return fcl_cpf; }
            set { SetPropertyValue<string>(nameof(cl_cpf), ref fcl_cpf, value); }
        }
        string fcl_telefone_recado;
        [ColumnDbDefaultValue("('------------')")]
        public string cl_telefone_recado
        {
            get { return fcl_telefone_recado; }
            set { SetPropertyValue<string>(nameof(cl_telefone_recado), ref fcl_telefone_recado, value); }
        }
        string fcl_nome_recado;
        public string cl_nome_recado
        {
            get { return fcl_nome_recado; }
            set { SetPropertyValue<string>(nameof(cl_nome_recado), ref fcl_nome_recado, value); }
        }
        string fcl_parentesco_recado;
        [Size(50)]
        public string cl_parentesco_recado
        {
            get { return fcl_parentesco_recado; }
            set { SetPropertyValue<string>(nameof(cl_parentesco_recado), ref fcl_parentesco_recado, value); }
        }
        char fcl_sexo;
        public char cl_sexo
        {
            get { return fcl_sexo; }
            set { SetPropertyValue<char>(nameof(cl_sexo), ref fcl_sexo, value); }
        }
        DateTime fcl_data_nascimento;
        public DateTime cl_data_nascimento
        {
            get { return fcl_data_nascimento; }
            set { SetPropertyValue<DateTime>(nameof(cl_data_nascimento), ref fcl_data_nascimento, value); }
        }
        string fcl_cep;
        [Size(10)]
        public string cl_cep
        {
            get { return fcl_cep; }
            set { SetPropertyValue<string>(nameof(cl_cep), ref fcl_cep, value); }
        }
        string fcl_endereco;
        [Size(200)]
        public string cl_endereco
        {
            get { return fcl_endereco; }
            set { SetPropertyValue<string>(nameof(cl_endereco), ref fcl_endereco, value); }
        }
        string fcl_complemento;
        public string cl_complemento
        {
            get { return fcl_complemento; }
            set { SetPropertyValue<string>(nameof(cl_complemento), ref fcl_complemento, value); }
        }
        string fcl_bairro;
        [Size(50)]
        public string cl_bairro
        {
            get { return fcl_bairro; }
            set { SetPropertyValue<string>(nameof(cl_bairro), ref fcl_bairro, value); }
        }
        string fcl_cidade;
        [Size(50)]
        public string cl_cidade
        {
            get { return fcl_cidade; }
            set { SetPropertyValue<string>(nameof(cl_cidade), ref fcl_cidade, value); }
        }
        string fcl_estado;
        [Size(50)]
        public string cl_estado
        {
            get { return fcl_estado; }
            set { SetPropertyValue<string>(nameof(cl_estado), ref fcl_estado, value); }
        }
        [Association(@"tb_servicosReferencestb_clientes")]
        public XPCollection<tb_servicos> tb_servicoss { get { return GetCollection<tb_servicos>(nameof(tb_servicoss)); } }
    }

}
