//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XPOCollection_Teste.standby_org
{

    public partial class tb_servicos : XPLiteObject
    {
        int fsv_id;
        [Key(true)]
        public int sv_id
        {
            get { return fsv_id; }
            set { SetPropertyValue<int>(nameof(sv_id), ref fsv_id, value); }
        }
        int fsv_ordem_serv;
        public int sv_ordem_serv
        {
            get { return fsv_ordem_serv; }
            set { SetPropertyValue<int>(nameof(sv_ordem_serv), ref fsv_ordem_serv, value); }
        }
        DateTime fsv_data;
        public DateTime sv_data
        {
            get { return fsv_data; }
            set { SetPropertyValue<DateTime>(nameof(sv_data), ref fsv_data, value); }
        }
        tb_clientes fsv_cl_idcliente;
        [Association(@"tb_servicosReferencestb_clientes")]
        public tb_clientes sv_cl_idcliente
        {
            get { return fsv_cl_idcliente; }
            set { SetPropertyValue<tb_clientes>(nameof(sv_cl_idcliente), ref fsv_cl_idcliente, value); }
        }
        string fsv_tipo_aparelho;
        [Size(50)]
        public string sv_tipo_aparelho
        {
            get { return fsv_tipo_aparelho; }
            set { SetPropertyValue<string>(nameof(sv_tipo_aparelho), ref fsv_tipo_aparelho, value); }
        }
        string fsv_marca;
        [Size(50)]
        public string sv_marca
        {
            get { return fsv_marca; }
            set { SetPropertyValue<string>(nameof(sv_marca), ref fsv_marca, value); }
        }
        string fsv_aparelho;
        [Size(50)]
        [ColumnDbDefaultValue("('-----------------')")]
        public string sv_aparelho
        {
            get { return fsv_aparelho; }
            set { SetPropertyValue<string>(nameof(sv_aparelho), ref fsv_aparelho, value); }
        }
        string fsv_cor;
        [Size(50)]
        public string sv_cor
        {
            get { return fsv_cor; }
            set { SetPropertyValue<string>(nameof(sv_cor), ref fsv_cor, value); }
        }
        string fsv_mei_serialnumber;
        [Size(50)]
        public string sv_mei_serialnumber
        {
            get { return fsv_mei_serialnumber; }
            set { SetPropertyValue<string>(nameof(sv_mei_serialnumber), ref fsv_mei_serialnumber, value); }
        }
        string fsv_defeito;
        [Size(300)]
        [ColumnDbDefaultValue("('-----------------')")]
        public string sv_defeito
        {
            get { return fsv_defeito; }
            set { SetPropertyValue<string>(nameof(sv_defeito), ref fsv_defeito, value); }
        }
        string fsv_servico;
        [Size(300)]
        [ColumnDbDefaultValue("('-----------------')")]
        public string sv_servico
        {
            get { return fsv_servico; }
            set { SetPropertyValue<string>(nameof(sv_servico), ref fsv_servico, value); }
        }
        string fsv_senha;
        [ColumnDbDefaultValue("('-----------------')")]
        public string sv_senha
        {
            get { return fsv_senha; }
            set { SetPropertyValue<string>(nameof(sv_senha), ref fsv_senha, value); }
        }
        string fsv_situacao;
        [Size(8000)]
        [ColumnDbDefaultValue("('-----------------')")]
        public string sv_situacao
        {
            get { return fsv_situacao; }
            set { SetPropertyValue<string>(nameof(sv_situacao), ref fsv_situacao, value); }
        }
        string fsv_acessorios;
        [Size(8000)]
        [ColumnDbDefaultValue("('-----------------')")]
        public string sv_acessorios
        {
            get { return fsv_acessorios; }
            set { SetPropertyValue<string>(nameof(sv_acessorios), ref fsv_acessorios, value); }
        }
        decimal fsv_valorservico;
        [ColumnDbDefaultValue("((0.00))")]
        public decimal sv_valorservico
        {
            get { return fsv_valorservico; }
            set { SetPropertyValue<decimal>(nameof(sv_valorservico), ref fsv_valorservico, value); }
        }
        decimal fsv_valorpeca;
        [ColumnDbDefaultValue("((0.00))")]
        public decimal sv_valorpeca
        {
            get { return fsv_valorpeca; }
            set { SetPropertyValue<decimal>(nameof(sv_valorpeca), ref fsv_valorpeca, value); }
        }
        decimal fsv_lucro;
        [ColumnDbDefaultValue("((0.00))")]
        public decimal sv_lucro
        {
            get { return fsv_lucro; }
            set { SetPropertyValue<decimal>(nameof(sv_lucro), ref fsv_lucro, value); }
        }
        int fsv_status;
        [ColumnDbDefaultValue("((1))")]
        public int sv_status
        {
            get { return fsv_status; }
            set { SetPropertyValue<int>(nameof(sv_status), ref fsv_status, value); }
        }
        int fsv_ativo;
        [ColumnDbDefaultValue("((1))")]
        public int sv_ativo
        {
            get { return fsv_ativo; }
            set { SetPropertyValue<int>(nameof(sv_ativo), ref fsv_ativo, value); }
        }
        DateTime fsv_data_conclusao;
        public DateTime sv_data_conclusao
        {
            get { return fsv_data_conclusao; }
            set { SetPropertyValue<DateTime>(nameof(sv_data_conclusao), ref fsv_data_conclusao, value); }
        }
        DateTime fsv_previsao_entrega;
        public DateTime sv_previsao_entrega
        {
            get { return fsv_previsao_entrega; }
            set { SetPropertyValue<DateTime>(nameof(sv_previsao_entrega), ref fsv_previsao_entrega, value); }
        }
        int fsv_existe_um_prazo;
        public int sv_existe_um_prazo
        {
            get { return fsv_existe_um_prazo; }
            set { SetPropertyValue<int>(nameof(sv_existe_um_prazo), ref fsv_existe_um_prazo, value); }
        }
        byte[] fsv_senha_pattern;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] sv_senha_pattern
        {
            get { return fsv_senha_pattern; }
            set { SetPropertyValue<byte[]>(nameof(sv_senha_pattern), ref fsv_senha_pattern, value); }
        }
        int fsv_cor_tempo;
        public int sv_cor_tempo
        {
            get { return fsv_cor_tempo; }
            set { SetPropertyValue<int>(nameof(sv_cor_tempo), ref fsv_cor_tempo, value); }
        }
        string fsv_tempo_para_entregar;
        [Size(10)]
        public string sv_tempo_para_entregar
        {
            get { return fsv_tempo_para_entregar; }
            set { SetPropertyValue<string>(nameof(sv_tempo_para_entregar), ref fsv_tempo_para_entregar, value); }
        }
        string fsv_relato_cliente;
        [Size(8000)]
        public string sv_relato_cliente
        {
            get { return fsv_relato_cliente; }
            set { SetPropertyValue<string>(nameof(sv_relato_cliente), ref fsv_relato_cliente, value); }
        }
        string fsv_condicoes_balcao;
        [Size(5000)]
        public string sv_condicoes_balcao
        {
            get { return fsv_condicoes_balcao; }
            set { SetPropertyValue<string>(nameof(sv_condicoes_balcao), ref fsv_condicoes_balcao, value); }
        }
        string fsv_avaliacao_servico;
        [Size(20)]
        public string sv_avaliacao_servico
        {
            get { return fsv_avaliacao_servico; }
            set { SetPropertyValue<string>(nameof(sv_avaliacao_servico), ref fsv_avaliacao_servico, value); }
        }
    }

}
